CREATE DATABASE [$(MSSQL_DB)];
GO
USE [$(MSSQL_DB)];
GO

CREATE LOGIN [$(MSSQL_USER)] WITH PASSWORD='$(MSSQL_PASSWORD)', CHECK_POLICY=OFF, CHECK_EXPIRATION=OFF;
GO
CREATE USER [$(MSSQL_USER)] FOR LOGIN [$(MSSQL_USER)];
GO
ALTER ROLE db_owner ADD MEMBER [$(MSSQL_USER)];
GO
